# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/hildeb47/proj/ECE1373_GhostSynth/mods/converter/converter/solution1/impl/verilog/converter.xdc

# IP: ip/converter_ap_fmul_2_max_dsp_32/converter_ap_fmul_2_max_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==converter_ap_fmul_2_max_dsp_32 || ORIG_REF_NAME==converter_ap_fmul_2_max_dsp_32}]
